# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-15 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('userpwd', models.CharField(max_length=32)),
                ('permissions', models.CharField(max_length=32)),
            ],
        ),
    ]
